# Generated by Django 4.1.1 on 2023-02-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('Product_name', models.TextField(help_text='Ürün adını giriniz.', max_length=250, verbose_name='Ürün Adı')),
                ('Product_price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Ürün Fiyatı')),
                ('Product_link', models.URLField(max_length=250, unique=True, verbose_name='Ürün Link')),
                ('Product_image', models.URLField(max_length=250, null=True, verbose_name='Ürünün Resmi')),
                ('Product_site', models.CharField(max_length=30, verbose_name='Ürünün Satıcısı')),
                ('Product_control', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
